export const MEETING_ROOM_LIST_REQUEST = 'MEETING_ROOM_LIST_REQUEST'
export const MEETING_ROOM_LIST_SUCCESS = 'MEETING_ROOM_LIST_SUCCESS'
export const MEETING_ROOM_LIST_FAIL = 'MEETING_ROOM_LIST_FAIL'

export const MEETING_ROOM_DETAILS_REQUEST = 'MEETING_ROOM_DETAILS_REQUEST'
export const MEETING_ROOM_DETAILS_SUCCESS = 'MEETING_ROOM_DETAILS_SUCCESS'
export const MEETING_ROOM_DETAILS_FAIL = 'MEETING_ROOM_DETAILS_FAIL'

export const MEETING_ROOM_AVAILABILITY_REQUEST = 'MEETING_ROOM_AVAILABILITY_REQUEST'
export const MEETING_ROOM_AVAILABILITY_SUCCESS = 'MEETING_ROOM_AVAILABILITY_SUCCESS'
export const MEETING_ROOM_AVAILABILITY_FAIL = 'MEETING_ROOM_AVAILABILITY_FAIL'

export const MEETING_ROOM_BOOKING_REQUEST = 'MEETING_ROOM_BOOKING_REQUEST'
export const MEETING_ROOM_BOOKING_SUCCESS = 'MEETING_ROOM_BOOKING_SUCCESS'
export const MEETING_ROOM_BOOKING_FAIL = 'MEETING_ROOM_BOOKING_FAIL'