export const MEETING_ROOM_LIST_REQUEST = 'MEETING_ROOM_LIST_REQUEST'
export const MEETING_ROOM_LIST_SUCCESS = 'MEETING_ROOM_LIST_SUCCESS'
export const MEETING_ROOM_LIST_FAIL = 'MEETING_ROOM_LIST_FAIL'